USE colombo;

SELECT LINE FROM (
	SELECT -5 AS ORDINAL_POSITION,
		N'USE rutkowski;' AS LINE

	UNION ALL

	SELECT -4 AS ORDINAL_POSITION,
		N'GO' AS LINE

	UNION ALL

	SELECT -3 AS ORDINAL_POSITION,
		N'IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N''Raport_sprzedazy_1999'')' AS LINE

	UNION ALL

	SELECT -2 AS ORDINAL_POSITION,
		N'    DROP VIEW dbo.Raport_sprzedazy_1999;' AS LINE

	UNION ALL

	SELECT -1 AS ORDINAL_POSITION,
		N'GO' AS LINE

	UNION ALL

	SELECT 0 AS ORDINAL_POSITION,
		N'CREATE VIEW dbo.Raport_sprzedazy_1999 AS' AS LINE

	UNION ALL

	SELECT ORDINAL_POSITION,
		CASE WHEN ORDINAL_POSITION = 1 THEN N'    SELECT '
			ELSE N'        ' END
		+ N'CAST(NULL AS ' + DATA_TYPE
		+ CASE WHEN DATA_TYPE LIKE N'%char' THEN N'(' + CAST(CHARACTER_MAXIMUM_LENGTH AS nvarchar(10)) + N')'
			ELSE N'' END
		+ N') AS ' + COLUMN_NAME
		+ CASE WHEN ORDINAL_POSITION < (
				SELECT MAX(ORDINAL_POSITION)
				FROM INFORMATION_SCHEMA.COLUMNS
				WHERE TABLE_NAME = N'SalesReport1999'
			) THEN N','
			ELSE N'' END
			AS LINE
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = N'SalesReport1999'

	UNION ALL

	SELECT 998 AS ORDINAL_POSITION,
		N'GO' AS LINE

	UNION ALL

	SELECT 999 AS ORDINAL_POSITION,
		N'SELECT * FROM dbo.Raport_sprzedazy_1999' AS LINE
) AS X
ORDER BY ORDINAL_POSITION
